server {
    listen 80;
    listen 8080;
    server_name _;

    root /var/www/html;
    autoindex on;            
    client_max_body_size 100M;

    server_tokens on;         

    location / {
        try_files $uri $uri/ =404;
    }
}
